version: '3.5'

services:
  node:
    image: node:18.2.0
    container_name: insomniak-vue-starter
    working_dir: /var/www/
    environment:
      TZ: Europe/Paris
      DEBIAN_FRONTEND: noninteractive
    command: /bin/bash -c "yarn dev"
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/